
const TZ="America/Toronto";
function parts(date=new Date()){const a=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(date);const o={};a.forEach(p=>o[p.type]=p.value);return o;}
function today(offset=0){const p=parts();const d=new Date(`${p.year}-${p.month}-${p.day}T12:00:00`);d.setDate(d.getDate()-offset);return d.toISOString().slice(0,10);}
function currentShift(){const p=parts();const d=new Date(`${p.year}-${p.month}-${p.day}T12:00:00`);if(Number(p.hour)<7)d.setDate(d.getDate()-1);return d.toISOString().slice(0,10);}
function mins(t){const m=String(t||"").match(/^([0-9]{1,2}):([0-9]{2})/);return m?Number(m[1])*60+Number(m[2]):-1;}
function shiftDate(date,time){const d=new Date(`${date||today()}T12:00:00`);const n=mins(time);if(n>=0&&n<420)d.setDate(d.getDate()-1);return d.toISOString().slice(0,10);}
function clean(v){return String(v||"").replace(/<br\s*\/?>/gi,"\n").replace(/<\/t[dh]>/gi,"|").replace(/<\/tr>/gi,"\n").replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();}
function units(t){return Array.from(new Set((String(t||"").match(/\b[A-Z]{1,4}\d{2,4}[A-Z]?\b/g)||[])));}
function rows(html){return (String(html||"").match(/<tr[\s\S]*?<\/tr>/gi)||[]).map(r=>(r.match(/<t[dh][^>]*>[\s\S]*?<\/t[dh]>/gi)||[]).map(clean).filter(Boolean)).filter(r=>r.length);}
function parse(html,truck){const out=[];for(const cells of rows(html)){const joined=cells.join(" | ");const i=cells.findIndex(c=>/^\d{4}-\d{2}-\d{2}\s+\d{1,2}:\d{2}/.test(c));if(i<0)continue;const dt=cells[i].match(/(\d{4}-\d{2}-\d{2})\s+(\d{1,2}:\d{2})/);if(!dt)continue;const rawDate=dt[1], time=dt[2], sd=shiftDate(rawDate,time);let u=units(cells.slice(i+4).join(" "));if(!u.length)u=units(joined);if(!u.length)u=[truck.toUpperCase()];out.push({date:sd,rawDate,shiftDate:sd,time,type:cells[i+1]||"Call",address:[cells[0]||"",cells[1]||""].filter(Boolean).join(" / "),alarmLevel:cells[i+2]||"",area:cells[i+3]||"",units:u});}return out;}
module.exports=async function handler(req,res){const truck=String((req.query&&req.query.truck)||"p334").toLowerCase().replace(/[^a-z0-9]/g,"");const days=Math.min(Number((req.query&&req.query.days)||3),14);try{const r=await fetch("https://asc-group.org/tfs/view.php?truck="+encodeURIComponent(truck),{headers:{"user-agent":"Mozilla/5.0 Station334PWA","accept":"text/html"}});const html=await r.text();let calls=parse(html,truck);const allowed=new Set();const start=new Date(currentShift()+"T12:00:00");for(let i=0;i<days;i++){const d=new Date(start);d.setDate(d.getDate()-i);allowed.add(d.toISOString().slice(0,10));}calls=calls.filter(c=>allowed.has(c.shiftDate)||allowed.has(c.rawDate)).slice(0,250);res.setHeader("cache-control","no-store");res.status(200).json({source:"live",platform:"vercel",timezone:TZ,currentShift:currentShift(),truck:truck.toUpperCase(),days,calls});}catch(e){res.setHeader("cache-control","no-store");res.status(200).json({source:"error",platform:"vercel",note:String(e&&e.message?e.message:e),calls:[]});}};
